### ISSUE TITLE
Make a different script module that handles graphs

### ISSUE THREAD

**Issue by TheBlocks** [TheBlocks/AstroMilano#16]
plot_graph() doesn't really belong in detect_humans.py
We should put it in a different script. The graph module should be useful since we'll be able to make graphs of anything, not just humidity.

Self note: `plot_graphs() if graph_imported else pass`

Previous issue:
Using matplotlib
Saves image to SD card of Astro Pi
Add maximum x and y axis values (calculate from list of given values)
Call function every 10 minutes (to avoid having too much lag)

**Comment by MobFactory** [comment]
have you done this?

**Comment by TheBlocks** [comment]
Not yet. :P
