### ISSUE TITLE
Discarding anomalies

### ISSUE THREAD

**Issue by TheBlocks** [TheBlocks/AstroMilano#17]
We have to have a function that discards anomalous results (e.g. extreme temperatures).

Make a function that takes in a list of (float) values and discards anomalous results. It then returns the list without anomalies.

Mr. Bowman said something about 3 standard deviations... (Idk what that means)

**Comment by MobFactory** [comment]
Standard deviation is easy np. Its what i was planning to do. I'll do it over the weekend.
DO NOT DO THIS. I will do it.
Hehehheheheheh

**Comment by MobFactory** [comment]
PROBLEM SOLVED! BOOM!
