### ISSUE TITLE
Test to see if we can scroll text and have a background at the same time

### ISSUE THREAD

**Issue by MobFactory** [TheBlocks/AstroMilano#19]
This cannot be tested until we have the pi. The api documentation doesn't talk very much about this. We may need to create our own scrolling text with background by creating several gif's.

**Comment by TheBlocks** [comment]
Having a background would likely decrease readability, unless it we have a white background and black text.

**Comment by MobFactory** [comment]
Nah, You just need to put a black border around the white text

**Comment by TheBlocks** [comment]
It's an 8x8 screen. We don't have that much space. :P

**Comment by TheBlocks** [comment]
So... Does it work?

**Comment by TheBlocks** [comment]
Closed issue.
