### ISSUE TITLE
Find new way of detecting astronaut that does not require astronaut intervention

### ISSUE THREAD

**Issue by MobFactory** [TheBlocks/AstroMilano#25]
Maybe use the standard deviation to say something like:

If humidity is above average + (1 or 2 or 3 or 4 * the standard deviation) for more than 1 second (to account for anomalies)
Print Hello Astronaut

**Comment by TheBlocks** [comment]
I don't know what a standard deviation is. Haven't done it in maths yet. :P

**Comment by TheBlocks** [comment]
Variance issue opened instead
