### ISSUE TITLE
Make standard deviation its own function

### ISSUE THREAD

**Issue by TheBlocks** [TheBlocks/AstroMilano#27]
Putting it in get_baseline makes get_baseline too long.

Have a standard_deviation() function that takes in a list of numbers and returns the final average without anomalies and stuff. We write that final average to a file outside the function.

Make get_baseline() just return a list.

**Comment by MobFactory** [comment]
Got it. Ill do it.

**Comment by TheBlocks** [comment]
It should be like this:

```
with open("baseline_records.txt", "w") as f:
    baseline_values = get_baseline()
    f.write(standard_deviation(baseline_values ))
```

Or something similar.

**Comment by TheBlocks** [comment]
I'm not sure how what you wrote works, so you should do this. I've made a new branch for this.

**Comment by TheBlocks** [comment]
Standard deviation will not be needed anymore, because variance?
