### ISSUE TITLE
Use barometric pressure to also aid in detect humans

### ISSUE THREAD

**Issue by MobFactory** [TheBlocks/AstroMilano#3]
The barometric pressure would be relatively stable in an empty module. We should detect changes in it to aid in detecting humans.

**Comment by TheBlocks** [comment]
We can still code it, just not try it out.

**Comment by MobFactory** [comment]
Honestly im still not convinced that humidity can. My on earth tests show not that great results unless you are directly breathing on it.

**Comment by TheBlocks** [comment]
So are we using pressure to detect astronauts?

**Comment by TheBlocks** [comment]
nope and closed
