### ISSUE TITLE
How to detect humans?

### ISSUE THREAD

**Issue by MobFactory** [TheBlocks/AstroMilano#4]
We can take in values every 1/4 of a second for 30 seconds when the astronaut is gone. We can then get an average and set that as our baseline. We tell it to ignore anything that was in the range of the values (e.g. 1,2,3,4,5,6,7,8,9,10 The average of the values is 5.5 but we tell the program to ignore anything 5 below or above the program) If the humidity is above the baseline and range for more than 2 seconds we can then tell it to say there is a human there.
Drawing a graph would use up more processing power and we wouldn't be able to display it anyway. So this seems like a better method.
P.S. Obviously remove extreme values.

P.P.S. We cant test this till we get the pi.

**Comment by TheBlocks** [comment]
Graph: might get us extra points for initiative.
Also, m8 plz. I've been working on this for 2 days. Still a long way to go.

**Comment by MobFactory** [comment]
Also i saw this:

def get_astronaut_humidity():
    print("Please have 1 astronaut stay in the room for 1 minute.")
    # If button is pressed:  # So that we know an astronaut is near
    astronaut_list = []  # List used for keeping baseline data
    pholder_hum = 60  # Placeholder for testing without Astro Pi

The pi must be able to detect astronauts automatically. We cannot get them to interact

**Comment by MobFactory** [comment]
Also ik. I'm, just putting these things up so we dont forget when the time comes
